<strong>Welcome to Hypercities!</strong><p>

To complete your registration, you must read the Terms of Service set forth below, make sure you understand them, and certify to the statement below, indicating your acknowledgement and acceptance of these terms.<p>

<strong>Your Passwords and Account Security</strong>
<ol>
<li> You agree and understand that you are responsible for maintaining the confidentiality of passwords associated with any account you use to access the Services.</li>

<li> Accordingly, you agree that you will be solely responsible to Hypercities for all activities that occur under your account.</li>

<li> If you become aware of any unauthorized use of your password or of your account, you agree to notify Hypercities Administrator immediately.</li>
</ol>

<strong>Content in the Services</strong>
<ol>
<li> You understand that all information (such as data files, written text, photographs, audio files or videos) which you may have access to as part of, or through your use of, the Services are the sole responsibility of the person from which such content originated. All such information is referred to below as the "Content"</li>

<li> Hypercities reserves the right (but shall have no obligation) to pre-screen, review, flag, filter, modify, refuse or remove any or all Content from any Service.</li>

<li> You agree that you are solely responsible for (and that Hypercities has no responsibility to you or to any third party for) any Content that you create, transmit or display while using the Services and for the consequences of your actions (including any loss or damage which Hypermedia may suffer) by doing so.</li>

</ol>

<strong>Change to the Terms</strong>
<ol> 
<li> We reserve the right, at our sole discretion, to change, modify, add, or delete portions of these Terms of Service at any time without further notice. If we do this, we will post the changes to these Terms of Service on our website. Your continued use of the Service or the Site after any such changes constitutes your acceptance of the new Terms of Service.
</li>
</ol>
